name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for GitHub Pages
      run: |
        npm run build
        rm -rf docs
        cp -r dist/public docs
        sed -i 's|src="/assets/|src="./assets/|g' docs/index.html
        sed -i 's|href="/assets/|href="./assets/|g' docs/index.html
        find docs/assets -name "*.js" -exec sed -i 's|"/assets/|"./assets/|g; s|"/icons/|"./icons/|g; s|"/code-institute-logo.png"|"./code-institute-logo.png"|g; s|"/malmo-university-logo.png"|"./malmo-university-logo.png"|g; s|"/zambia-university-logo.png"|"./zambia-university-logo.png"|g' {} \;
        cp docs/index.html docs/404.html
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs